### ISSUE TITLE
Can't retrieve hidden file

### ISSUE THREAD

**Issue by kodie** [someguycrafting/picamo#2]
So I have a JPG image, and I've tried hiding multiple different files inside of it, however I cant retrieve the hidden file afterwards.

Running

```
node picamo -c hide -p test -i test.jpg -f logo/logo.png --nocomp
```

gets me

```
test.jpg.enc.jpg successfully written.
Image size: 4086464 bytes, camo image size: 4090839 bytes -> 1% increase
```

however after that running

```
node picamo -c show -p test -i test.jpg.enc.jpg --nocomp
```

gets me no response, no errors, and no new files written.

I've tried with a couple of different file combinations. Any ideas? Thank you.

**Comment by someguycrafting** [comment]
Hi @kodie. Could you please try it without the --nocomp option and check if you're able to retrieve the hidden file? Thanks.

**Comment by someguycrafting** [comment]
Closed as no response from he user. @kodie, please feel free to open a new issue if the problem persists.
